//POSTGRESQL
CREATE TABLE balance(
    id SERIAL PRIMARY KEY
    user_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE
    amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)