CREATE TYPE enum_commission AS ENUM ('AUCTION_WINNER', 'USER_DEPOSIT');

CREATE TABLE commission(
    id SERIAL PRIMARY KEY,
    type enum_commission NOT NULL,
    value DECIMAL(5,4) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TYPE enum_commission RENAME VALUE 'AUCTION_WINNER, USER_DEPOSIT' TO 'AUCTION_WINNER';
ALTER TYPE enum_commission ADD VALUE 'USER_DEPOSIT'

ALTER TABLE commission RENAME TO commission_rule