CREATE TABLE IF NOT EXISTS permission(
    id SERIAL PRIMARY KEY,
    action VARCHAR(200) NOT NULL CHECK(TRIM(name) <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);