CREATE TABLE IF NOT EXISTS session(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id),
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);