CREATE TABLE IF NOT EXISTS user_role(
    id SERIAL PRIMARY KEY,
    role_id INT NOT NULL REFERENCES role(id),
    user_id INT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);